package com.example.payment_event_simulator.Model;

import java.math.BigDecimal;
import java.time.Instant;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class BankPaymentEvent {

    private String eventId;            // Unique event I
    private String transactionId;     // Generated by bank
    private String bankRefId;          // Bank internal reference
    private BigDecimal amount;
    private String currency;           // INR, USD
    private String status;             // SUCCESS, FAILED, PENDING
    private Instant eventTime;         // When bank processed payment
}
