package com.example.event_ingestion.Model;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(
    name = "raw_events",
    uniqueConstraints = {
        @UniqueConstraint(
            name = "uk_event_source",
            columnNames = {"eventId", "source"}
        )
    },
    indexes = {
        @Index(name = "idx_raw_event_id", columnList = "eventId"),
        @Index(name = "idx_raw_transaction_id", columnList = "transactionId"),
        @Index(name = "idx_raw_status", columnList = "status")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RawEvent {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique ID generated by external system
     * Used for idempotency
     */
    @Column(nullable = false, updatable = false)
    private String eventId;

    /**
     * Source system of event
     * BANK / WALLET / MERCHANT
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, updatable = false)
    private EventSource source;

    /**
     * Business transaction ID
     * Used for reconciliation grouping
     */
    @Column(nullable = false, updatable = false)
    private String transactionId;

    /**
     * Full raw JSON payload
     */
    @Column(columnDefinition="TEXT",nullable = false, updatable = false)
    private String payload;

    /**
     * When ingestion service received the event
     */
    @Column(nullable = false, updatable = false)
    private Instant receivedAt;

    /**
     * Processing state of event
     * RECEIVED → PROCESSED / FAILED / INVALID
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private RawEventStatus status;
}