package com.example.event_ingestion.Model;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(
    name = "raw_events",
    uniqueConstraints = {
        @UniqueConstraint(name = "uk_raw_event_event_id", columnNames = "eventId")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RawEvent {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique ID generated by the external system
     * Used for deduplication
     */
    @Column(nullable = false, updatable = false)
    private String eventId;

    /**
     * Logical source of the event
     * WALLET / BANK / MERCHANT
     */
    @Column(nullable = false, updatable = false)
    @Enumerated(EnumType.STRING)
    private EventSource source;

    /**
     * Business transaction identifier
     * Used to correlate events
     */
    @Column(nullable = false, updatable = false)
    private String transactionId;

    /**
     * Full raw payload as received (JSON)
     */
    @Lob
    @Column(nullable = false, updatable = false)
    private String payload;

    /**
     * Time at which ingestion service received the event
     */
    @Column(nullable = false, updatable = false)
    private Instant receivedAt;
}
